### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by carlasantana302** [MyRainboww/Drag-Race-Simulator#1]
Im really loving the update while the owner is coming back, i have noticed that there is a change compared to the original one, and is the fact that the queens images and track record dont show up throughout the season (like episode by episode) and only do at the end of the season, could we add that feature? (or even just the track record episode by episode) i think it makes the experience more didactic and graphic.

Lovee lovee all the new features you added
Have a great day!

**Comment by MyRainboww** [comment]
Thank youu <3 I just did it! Haha
