### ISSUE TITLE
A question sorry

### ISSUE THREAD

**Issue by Naylenrodriguez** [MyRainboww/Drag-Race-Simulator#100]
![Screenshot_20220417-004840](https://user-images.githubusercontent.com/102640498/163701117-b0ab1463-49c7-4a56-8102-5c4a67765a1c.png)
![Screenshot_20220417-004846](https://user-images.githubusercontent.com/102640498/163701119-a3d43fba-df46-4839-95a6-6254efc9756f.png)

In situations like these shouldn't a revote happen? Or both of them be allowed to go back in? 👀

**Comment by MyRainboww** [comment]
Yes! That was my bad haha I forgot to add the revote to the return vote. Sorry!
