### ISSUE TITLE
Lip sync smackdown glitch 

### ISSUE THREAD

**Issue by Naylenrodriguez** [MyRainboww/Drag-Race-Simulator#109]
Is it going to be compatible with double sashays and shantays again?

**Comment by MyRainboww** [comment]
It was never compatible.

**Comment by Naylenrodriguez** [comment]
![Screenshot_20220423-183620](https://user-images.githubusercontent.com/102640498/164948229-dfbffaf9-2309-4aed-9c9b-b2414a2845bd.png)


Wdym? It was beforehand. It used to appear for me at least. Could it at least be fixed so we don't have to keep disabling it?

**Comment by Naylenrodriguez** [comment]
![Screenshot_20220423-192247](https://user-images.githubusercontent.com/102640498/164949259-3cff64e0-38ab-48db-b33b-abc9ff0546c2.png)


See

**Comment by Naylenrodriguez** [comment]
I just would've liked it to be compatible. So we can still get double shantays and sashays in regular and all star seasons
