### ISSUE TITLE
‘WIN’ Placement Question

### ISSUE THREAD

**Issue by moonglade547** [MyRainboww/Drag-Race-Simulator#154]
Hi, just a quick question. What exactly does a grey-blue ‘WIN’ placement mean on the track record? 

Thank you! 

![15C181B9-1E84-4D57-B78A-001077E4E216](https://user-images.githubusercontent.com/110580535/201490456-2c7482c6-f7df-4852-ac54-42357db9bc15.jpeg)

**Comment by MyRainboww** [comment]
The contestant was the Top All Star of the week and lost the lip sync against the "Lip Sync Assassin," but still had the power to eliminate one of the bottom queens due to a tie in the group voting.
