### ISSUE TITLE
Github format request

### ISSUE THREAD

**Issue by pythonines** [MyRainboww/Drag-Race-Simulator#17]
Do you think it'd be possible to add a changelog on your GitHub page so we would be able to see what changes were implemented? If it's too much work it's totally fine, I just like to see what's been changed whenever I visit the page. Thank you!

**Comment by ThawedMist** [comment]
I think they might take it off the to do list when they finish stuff, like with the Team Format they are gonna do soon i believe? but i swear it exists somewhere but i may be wrong

**Comment by MyRainboww** [comment]
I added it @pythonines , you were right I needed that!
