### ISSUE TITLE
Something Different!

### ISSUE THREAD

**Issue by TiwaGrande** [MyRainboww/Drag-Race-Simulator#19]
I had this idea of maybe having the lipstick choices and votes on the placements table.

Also this could tie into the interactive but I think it would be good for now too, but all of the lipstick choices are blurred out, same with votes and eliminated queens, so you can choose to see who the winners pick or who everyone voted for. I love the element of surprise and if I could go through the simulator with hidden eliminations and then click on them to see then that would be iconic!

Then with my first point you could see who picked who on a table underneath the main chart

sorry this was long, please continue being an icon!

**Comment by MyRainboww** [comment]
Hi! I will definetly add the lipstick choices and votes table in the sim! Thank you so much for letting me know.
Last part I didn't understand, what you mean with hidden eliminations?

**Comment by TiwaGrande** [comment]
I did think it would be confusing 💀 but basically

the eliminations where the the picture of the queen and name is, this would be where the winner picks the lipsticks, the votes and the all lipsync results have a blurred texture that u can click on or on a [Show] button and it would reveal! I have no idea if this is even possible but if so I think that could be really unique and sickening! 

Also please keep up the amazing work I live on this simulator lmao

**Comment by MyRainboww** [comment]
Oooh I get it! Hahaha yes thank you. I love that idea. Gonna do it too!

**Comment by TiwaGrande** [comment]
Omggg! Thank you! I’m very excited. I hope you don’t overwork yourself with the amount you have on your list though💀
