### ISSUE TITLE
Thank you for your work

### ISSUE THREAD

**Issue by ThawedMist** [MyRainboww/Drag-Race-Simulator#22]
Hi!! not an issue/question but i just wanted to say thank you for working on this, and i hope your school work isn't too hard!! <3

**Comment by MyRainboww** [comment]
Helloww! aww thank you <3. School's been hard but I think I might have some time for these next weeks!!

**Comment by ThawedMist** [comment]
> Helloww! aww thank you <3. School's been hard but I think I might have some time for these next weeks!!

I'm so glad!! I can't wait for the updates you always do so well with them!

**Comment by UntilDawna** [comment]
Yes! Thank you, have been loving the new updates.
