### ISSUE TITLE
Team challenges

### ISSUE THREAD

**Issue by chico545** [MyRainboww/Drag-Race-Simulator#23]
Hi!
Thank you for your hard hard work, im so grateful that you keep on updating this!
This is not really an issue, more like a question, i would love to know what are the team challenge conditions or how are they triggered? Im asking because ive done some simulations since the update, but no team challenges have happened!

Thanks in advance!

**Comment by MyRainboww** [comment]
Yes, I've noticed that too haha. 
They trigger if you have more than 5 queens and with a probability of 20% I think haha but I will increase that for sure in a few hours when I wake up.
