### ISSUE TITLE
Advice/Ideas

### ISSUE THREAD

**Issue by Sonofapreacherma** [MyRainboww/Drag-Race-Simulator#3]
For the season 14 girls some of it isn't really adding up to what we have seen for them such as the ball/ design challenges Angeria got bottom on a ball challenge when we know she can sew the Haus down along with Deja so i would maybe fix some of their scores and personally me i watch spoilers so i know some results so if you do want me to do it so you wouldn't have to i can so it can match up a little bit. Also, I was wondering if you could add more disqualifications to yours and also one where you can break like a bone or hurt yourself and get elim and also a dela one where the queen can self-eliminate herself. Please

**Comment by MyRainboww** [comment]
Yes, the s14 girls have a 7 in all of their stats and I'll update them once they show the last competing episode.
And yes! I didn't thought about that and I love the others ways to get out! Thank you.
