### ISSUE TITLE
non elim glitch

### ISSUE THREAD

**Issue by nickcostanzo** [MyRainboww/Drag-Race-Simulator#34]
i'm so sorry again for sending another issue, however i just have one question. a non bottoms happened during the first split premier of s14 & it kinda bugged out the whole sim afterwards. is there a way you could remove any twists like a 6 way lipsync, non bttm, etc from not happening during a split premiere? thank you and again i'm so sorry for sending issues

![Screenshot 2022-03-16 11 46 27 PM](https://user-images.githubusercontent.com/101535885/158733199-eae2b93d-719d-464f-9604-2e0ddc8132aa.png)

**Comment by MyRainboww** [comment]
Hi!! Someone just sent me this same bug!
I already fixed it! You will not see it again! :D
