### ISSUE TITLE
New queens

### ISSUE THREAD

**Issue by maybevalentina** [MyRainboww/Drag-Race-Simulator#38]
Hey! First of all, I really like the hard work you’ve putting on this sim cause I love the old one but was sad cuz was no longer being updated.

So, I wanna know if you have in your plans to add the Queens of the Universe cast to the sim. Even if it’s a singer competition, the system just looks alike with Drag Race and both are very related, so it would be cool to have they as a cast.

Second, can you bring Sharon Needles to the season 4 cast? I mean, there’s still a lot of problematic queens in the sim (like Karen From Finance) and she’s not that problematic tho, cause her accusations was fake and the people who made them said it.

Thank you (:

**Comment by MyRainboww** [comment]
Hi!! Thank you!, I'm so happy that you are enjoying the simulator!

I don't know about Queen of the Universe, as we didn't see how they design, act, improv, etc...
But let me think about it.

That's definetly a no.. but you can add them as a custom queen!
