### ISSUE TITLE
Ideas Part 2.

### ISSUE THREAD

**Issue by Sonofapreacherma** [MyRainboww/Drag-Race-Simulator#4]
I know you thinking like DAMN leave me alone why does this person keeps leaving stuff but I love this little game and another idea I have is adding storyline sometimes finding a way to do an untucked between like the safe and they are talking and being shady and arguing and some iconic moments like laganja moment and silky etc, and then ofc you can click proceed to go to like the top and bottom results and like after an episode when you click proceed after the track it can be like they are talking throwing shade etc like normal rpdr and then click procced again to go to the mini and the rest of the stuff, some more ideas just to add storyline and make the website even more fun.

**Comment by MyRainboww** [comment]
yes! I'm currently working on that!

**Comment by Sonofapreacherma** [comment]
Do you know when it will be done? Im so excited and can’t wait to do it

**Comment by MyRainboww** [comment]
no, I'm still learning how to do it haha so it's gonna take some time :(

**Comment by Sonofapreacherma** [comment]
No worries, thanks for the update!

**Comment by Sonofapreacherma** [comment]
I’m playing the simulator right now lol On Fri, Feb 4, 2022 at 1:35 PM
