### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by angieblowie** [MyRainboww/Drag-Race-Simulator#40]
hi! first of all i want to thank you for your updates, they have been nothing short of fabulous.

one small tweak i would suggest is changing the 'btm2/3/4/6' placements on the contestants' progress table to just simply 'btm' as sometimes it puts the wrong number in. i would also like to see 3-way-lipsyncs if possible please.

but keep doing what you are doing, your amazing x

**Comment by MyRainboww** [comment]
Hellowww! Thank you so much for those kind words! it mean a lot <3

I'm taking the table of queens of the wiki as a reference and I think the numbers are good to specify what happen. 
Can you send me a SS when it pt the wrong number on the table, please? So I can fix that up. 
3 way lipsyncs will be a reality in the sim in a few days!

Thank you so much again! <3

**Comment by angieblowie** [comment]
![2A3282FA-B051-40D3-AD95-E42C0D7CFB39](https://user-images.githubusercontent.com/101904680/159118901-9d953a43-de1e-48e2-a7cb-d276a1699593.jpeg)

there it is :)) i totally understand your point x

also, if you can see on the ball challenge pictured, ‘top2’ is there instead of ‘win’

thank you!!

**Comment by MyRainboww** [comment]
Thank you so much! I'm fixing that rn!
