### ISSUE TITLE
Just some suggestions

### ISSUE THREAD

**Issue by QueefQueen** [MyRainboww/Drag-Race-Simulator#44]
Now I have no idea about how hard coding is or anything like that but still I have some suggestions.
- Being able to pick the type of challenge the queens do each week?
- A mode where you can reveal each placement and result one by one, similar to the reveal of lipstick choices
- Lalaparuza thing from Season 14 to be a thing
- S14 queens stats updated

Other than that, I love this simulator keep updating it because its fierce.

**Comment by MyRainboww** [comment]
Hi!! thank you <3

I love all of your suggestions!
All of them are in my To do list!
