### ISSUE TITLE
Custom queen issues

### ISSUE THREAD

**Issue by ThawedMist** [MyRainboww/Drag-Race-Simulator#50]
![image](https://user-images.githubusercontent.com/98528306/159492451-104aa95d-eb22-4197-bd37-36e0d0db9ec3.png)

I was trying to use custom queens and it let me use images but this happens when i use them
![image](https://user-images.githubusercontent.com/98528306/159492616-622be40b-71a2-4125-b5e8-4bbb99993069.png)

**Comment by MyRainboww** [comment]
Hi! 
It probably means that the link that you gave is not an image! 
Send me a DM in Discord so I can help you better! **Rainbow#4283**

**Comment by ThawedMist** [comment]
> Hi! It probably means that the link that you gave is not an image! Send me a DM in Discord so I can help you better! **Rainbow#4283**

I believe it was but i will try again another day i may have just been in a silly goofy mood and did it wrong

**Comment by ThawedMist** [comment]
It works now so i will close this!
