### ISSUE TITLE
no progress button when a queen has returned x

### ISSUE THREAD

**Issue by angieblowie** [MyRainboww/Drag-Race-Simulator#56]
hi! thank you so much for updating again, great new additions x

i've attached an issue where the progress button isn't there when a queen has returned :)

best wishes
joseph x

![drag race issue](https://user-images.githubusercontent.com/101904680/160249834-54461d32-3917-47cc-bba2-679f5105a705.PNG)

**Comment by MyRainboww** [comment]
I'm so sorry! I forgot to add a line haha. I'm updating the sim in a minute and it will be fixed!
