### ISSUE TITLE
Suggestions + Thank You Letter

### ISSUE THREAD

**Issue by vicentcs** [MyRainboww/Drag-Race-Simulator#59]
Hey! I'm loving the new updates and I congratulate you on it! 
I just read your ''To do list'' and I just wanted to say which features I am most looking forward to play:
-Untucked (I'm really excited to see how this is like, I think this will make the simulator funnier and more dramatic)

-Be Rupaul/ Interactive mode (This is perfect for how I would like to play, basically, making the decisions as the top and the bottoms, who wins the lipsync, how many lipsync, the challenge...)

-The improvement of team challenges (acting, improv and girl groups) , like see the teams and that stuff and basically more detailed challenges would be very nice!

-Miss Congeniality title (I think this feature will be fun for the gameplay)
 
-PS: I don't know if these things are easy to code but I suggest them anyway hehehe

Keep working! You are making a really good job with this simulator. Can't wait for more updates.
A hug!

**Comment by MyRainboww** [comment]
Thank you so much <3
