### ISSUE TITLE
Chocolate Bar Twist in double premeire 

### ISSUE THREAD

**Issue by hockeybdk** [MyRainboww/Drag-Race-Simulator#62]
Hello! I noticed when playing the new amazing update the there is a slight problem. Since the chocolate bars are given before the third episode (where someone actually goes home) the gold bar can be wasted when they would come back anyways. Thanks for your help
<img width="550" alt="Screen Shot 2022-03-27 at 10 52 13 PM" src="https://user-images.githubusercontent.com/102498225/160319073-0690e592-23f3-418a-b83b-2b46bd8d4c2f.png">
!

**Comment by MyRainboww** [comment]
Thank you for letting me know! I'm fixing that right now!

**Comment by MyRainboww** [comment]
fixed
