### ISSUE TITLE
Lalaparuza issue

### ISSUE THREAD

**Issue by pythonines** [MyRainboww/Drag-Race-Simulator#7]
Lalaparuza only works under specific circumstances, normal premise, must be lip sync for legacy finale format and disable double shantay/double sashay. And even under these circumstances it doesn't work sometimes, if you have more than 10 queens on your simulation the screen will be cut off at the bottom and you will be unable to scroll down to click the continue button. 

ps, thank you so much for updating this simulator, you're doing great work with it! <
<img width="1440" alt="Screen Shot 2022-02-07 at 12 28 03 PM" src="https://user-images.githubusercontent.com/99209510/152849321-2cc3b625-7246-41b5-a0d5-de12c8c60fbd.png">
3

**Comment by MyRainboww** [comment]
It's fixed, it doesn't die anymore I'd like to think! Sorry for the problems! The only thing is that it needs to be with lipsync for your legacy format for now! I'm sorry!
