### ISSUE TITLE
Makeover challenge suggestions 

### ISSUE THREAD

**Issue by Naylenrodriguez** [MyRainboww/Drag-Race-Simulator#71]
If you can, can you put all the variations of the makeover challenges throughout the years into the challenges. Like in season 13, we will have contestants making over each other and have two winners. While we can do the regular ones were it's one winner each.

Just a suggestion message me if you need me o explain more

**Comment by MyRainboww** [comment]
I like that idea! Thank you!

**Comment by Naylenrodriguez** [comment]
Yay ty
