### ISSUE TITLE
Bug with the custom 

### ISSUE THREAD

**Issue by giaopendoors** [MyRainboww/Drag-Race-Simulator#74]
I put all the cast with the random stats and when I made the season, the cast duplicates (the original and the custom) 
I don’t think I have to turn off something…

sorry for my English.

**Comment by MyRainboww** [comment]
Hi, your english is excellent! And yes, I just fixed that, thank you!!

**Comment by giaopendoors** [comment]
Thank you. (!!!!!)
and thanks for all the work you put in this
