### ISSUE TITLE
Mini challenge questions 

### ISSUE THREAD

**Issue by Naylenrodriguez** [MyRainboww/Drag-Race-Simulator#77]
Shouldn't the girl who wins the mini challenge get some extra points. Even if it's by one point. I would love if you would add that.

**Comment by MyRainboww** [comment]
Yes, but right now the mini challenge winners are random so I don't think it would be fairish to giv them extra points.

**Comment by Naylenrodriguez** [comment]
I meant by literally 1 point. I don't see how that's unfair, but🤷‍♂️
