### ISSUE TITLE
Can you add a search button? 

### ISSUE THREAD

**Issue by Naylenrodriguez** [MyRainboww/Drag-Race-Simulator#78]
You think it's possible to add a search button after you pick how many queens you want per season? So that way you don't have to go scrolling throughout the list.

For example if I put a 20 queen season, and I want a certain Queen there can just be a search bar next to it and I can just write Jimbo and she'll appear and I click it.

**Comment by MyRainboww** [comment]
Yes, I have to add that feature! Thank you. It is annoying cause there are like +300 drag artists now.

**Comment by Naylenrodriguez** [comment]
Yes ty
