### ISSUE TITLE
AS6 issue

### ISSUE THREAD

**Issue by freddaferguson** [MyRainboww/Drag-Race-Simulator#88]
All Stars 6 isn't loading and there is an error message about formats

**Comment by MyRainboww** [comment]
Thank you! I just fixed, the error message pops up when you don't follow the settings!

**Comment by freddaferguson** [comment]
it is still happening right before the reveal

**Comment by MyRainboww** [comment]
omg I'm so dumb hahaha thank you!

**Comment by MyRainboww** [comment]
I think now it should be fine

**Comment by Naylenrodriguez** [comment]
Hey shouldn't, every girl group challenge have 4 winners or more. Idk it seems weird to have only one winner in that challenge. The whole point is to spread wins.
