### ISSUE TITLE
3way, double shantay glitch(?)

### ISSUE THREAD

**Issue by nickcostanzo** [MyRainboww/Drag-Race-Simulator#89]
hi! ty for these great updates & i'm very excited for untucked to be finished! quick questions though, for the 3 way lip sync, is there a way you could activate it like you can with a 6 way?? cuz i tried many times and i can't. also, i haven't seen any double shantays happen which they happen to me pretty often at all today ever since the "kandy wait" update, idk if that's just me, but i would like to know if it's just a glitch or you just made it harder to get double shantays now. besides that, everything's great, thank you! :)

**Comment by MyRainboww** [comment]
No, you can't activate a bottom 3, sorry! :(
And yes, now is harder to get a double shantay, and even more a Kandy wait haha!! Good luck!

Thank you so much! <3
